@baseurl=http://localhost:3333
@acessToken = {{AUTHENTICATION.response.body.acess_token}}

# @name CREATE-ACCOUNT
POST {{baseurl}}/accounts
content-type: application/json

{
    "name": "john doe",
    "password": "123456",
    "email":"john@example.com"
}

### 

# @name AUTHENTICATION
POST {{baseurl}}/sessions
content-type: application/json

{
    "password": "123456",
    "email":"john@example.com"
}

### 

# @name CREATE_QUESTION
POST {{baseurl}}/questions
content-type: application/json
Authorization: Bearer {{acessToken}}

{
  "title": "Nova pergunta",
  "content": "Teste"
}


### 

# @name FTECH_RECENTS_QUESTIONS
GET {{baseurl}}/questions
content-type: application/json
Authorization: Bearer {{acessToken}}

